module.exports = {
  hint: {
    'tagname-lowercase': true,
    'attr-lowercase': true,
    'attr-value-double-quotes': false,
    'attr-value-not-empty': true,
    'attr-no-duplication': true,
    'doctype-first': true,
    'tag-pair': true,
    'empty-tag-not-self-closed': true,
    'spec-char-escape': true,
    'id-unique': true,
    'src-not-empty': true,
    'title-require': true,
    'alt-require': true,
    'doctype-html5': true,
    'id-class-value': false,
    'style-disabled': false,
    'inline-style-disabled': false,
    'inline-script-disabled': false,
    'space-tab-mixed-disabled': 'space',
    'id-class-ad-disabled': false,
    'href-abs-or-rel': false,
    'attr-unsafe-chars': true,
    'head-script-disabled': true
  },
  beautify: {
    indent_size: 2,
    indent_char: ' ',
    eol: '\n',
    indent_level: 0,
    indent_with_tabs: false,
    preserve_newlines: false,
    max_preserve_newlines: 2,
    jslint_happy: false,
    space_after_anon_function: false,
    brace_style: 'collapse',
    keep_array_indentation: false,
    keep_function_indentation: false,
    space_before_conditional: true,
    break_chained_methods: false,
    eval_code: false,
    unescape_strings: false,
    wrap_line_length: 0,
    wrap_attributes: 'auto',
    wrap_attributes_indent_size: 4,
    end_with_newline: true,
  },
  minify: {
    collapseWhitespace : true,
    minifyCSS: true,
    minifyJS: true,
    removeComments : true,
  }
};
